parameters:
  - name: environmentName
    type: string
  - name: serviceConnectionName
    type: string
  - name: functionAppName
    type: string
  - name: artifactName
    type: string
  - name: jobName
    type: string
  - name: jobDisplayName
    type: string
  - name: deploymentMethod
    type: string
    default: auto

jobs:
  - deployment: Deploy_${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    environment: ${{ parameters.environmentName }}
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: ${{ parameters.artifactName }}

            - task: AzureFunctionApp@2
              displayName: Deploy to Azure Function App
              inputs:
                azureSubscription: ${{ parameters.serviceConnectionName }}
                appType: functionAppLinux
                appName: ${{ parameters.functionAppName }}
                package: $(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.artifactName }}.zip
                deploymentMethod: ${{ parameters.deploymentMethod }}
